name: Sync Master to Pre-Release

on:
  push:
    branches:
      - master
jobs:
  sync-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SHOP_EASE_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name "gulbin-dev"
          git config --global user.email "${{  secrets.EMAIL_TOKEN  }}"

      - name: Merge Master into Pre-Release
        run: |
          # Fetch the latest tracking states from GitHub
          git fetch origin

          # Switch to the pre-release branch
          git checkout pre-release

          # Merge master. -X theirs ensures master's versions overwrite pre-release.
          # CRITICAL: [skip ci] prevents Release Please from creating endless loop PRs on pre-release.
          git merge origin/master -X theirs -m "chore: sync master into pre-release [skip ci]"

          # Push the synchronized code back up
          git push origin pre-release
