name: release-please

on:
  push:
    branches:
      - pre-release

  pull_request:
    branches:
      - master
      - pre-release

permissions:
  contents: write
  pull-requests: write
  issues: write
  statuses: write

jobs:
  release-stable:
    if: github.ref_name == 'master' || github.base_ref == 'master'
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.SHOP_EASE_TOKEN }}
          target-branch: master
          release-type: node
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  release-beta:
    if: github.ref_name == 'pre-release' || github.base_ref == 'pre-release'
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.SHOP_EASE_TOKEN }}
          target-branch: pre-release
          release-type: node
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  deploy-stable:
    needs: release-stable
    if: github.ref_name == 'master' && needs.release-stable.outputs.release_created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g vercel@latest
      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  deploy-beta:
    needs: release-beta
    if: github.ref_name == 'pre-release' && needs.release-beta.outputs.release_created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g vercel@latest
      - run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
